import { ASTNode } from '../types';

interface Props {
  node: ASTNode;
}

const W = 480;
const H = 380;

function getConLabels(node: ASTNode): string[] {
  return (node.children || [])
    .filter(c => c.kind === 'Con')
    .map(c => c.label?.split(' ')[0] || c.label || '?');
}

function getPConLabels(node: ASTNode): { name: string; face0: string; face1: string }[] {
  return (node.children || [])
    .filter(c => c.kind === 'PCon')
    .map(c => ({
      name: c.label?.split('@')[0] || c.label || '?',
      face0: c.children?.[0]?.label || '?',
      face1: c.children?.[1]?.label || '?',
    }));
}

function detectHITType(node: ASTNode): string {
  const name = node.label || '';
  if (name.includes('S1') || name.includes('Circle')) return 'S1';
  if (name.includes('Torus') || name.includes('T2')) return 'Torus';
  if (name.includes('Susp')) return 'Suspension';
  if (name.includes('Trunc') || name.includes('Prop')) return 'Truncation';
  return 'generic';
}

function renderS1Diagram(node: ASTNode) {
  const cx = W / 2;
  const cy = H / 2 + 10;
  const r = 100;

  return (
    <g>
      {/* The circle */}
      <circle cx={cx} cy={cy} r={r}
        fill="none" stroke="#f7768e" strokeWidth="3" />

      {/* Loop arrow */}
      <path d={`M ${cx + r * 0.7} ${cy - r * 0.7}
        A ${r * 0.3} ${r * 0.3} 0 1 1 ${cx + r * 0.71} ${cy - r * 0.69}`}
        fill="none" stroke="#ff7a93" strokeWidth="2"
        markerEnd="url(#hit-arrow)" />

      {/* Base point */}
      <circle cx={cx + r} cy={cy} r="10" fill="#9ece6a" stroke="#0a0a0f" strokeWidth="2.5" />
      <text x={cx + r + 20} y={cy + 4} className="geo-label" fill="#9ece6a" fontWeight="700">
        base
      </text>

      {/* Loop label */}
      <text x={cx + r * 0.45} y={cy - r * 0.85} textAnchor="middle"
        className="geo-label" fill="#ff7a93" fontWeight="600">
        loop
      </text>

      {/* Type annotation */}
      <text x={cx} y={40} textAnchor="middle" className="geo-title">
        S¹ (Circle)
      </text>
      <text x={cx} y={58} textAnchor="middle" className="geo-annotation" fill="#f7768e">
        base : S¹ &nbsp;&nbsp;|&nbsp;&nbsp; loop : Path S¹ base base
      </text>

      {/* Fundamental group note */}
      <text x={cx} y={H - 24} textAnchor="middle" className="geo-annotation">
        π₁(S¹) ≅ ℤ — generated by the loop
      </text>
    </g>
  );
}

function renderTorusDiagram() {
  const cx = W / 2;
  const cy = H / 2 + 10;

  return (
    <g>
      {/* Rectangle body */}
      <rect x={cx - 120} y={cy - 80} width={240} height={160}
        fill="#7aa2f7" fillOpacity="0.06" stroke="#7aa2f7" strokeWidth="2" strokeDasharray="8 4" />

      {/* Top edge (loop a) */}
      <line x1={cx - 120} y1={cy - 80} x2={cx + 120} y2={cy - 80}
        stroke="#f7768e" strokeWidth="3" markerEnd="url(#hit-arrow)" />
      <text x={cx} y={cy - 92} textAnchor="middle" className="geo-label" fill="#f7768e" fontWeight="600">
        a
      </text>

      {/* Bottom edge (loop a) */}
      <line x1={cx - 120} y1={cy + 80} x2={cx + 120} y2={cy + 80}
        stroke="#f7768e" strokeWidth="3" markerEnd="url(#hit-arrow)" />
      <text x={cx} y={cy + 98} textAnchor="middle" className="geo-label" fill="#f7768e" fontWeight="600">
        a
      </text>

      {/* Left edge (loop b) */}
      <line x1={cx - 120} y1={cy + 80} x2={cx - 120} y2={cy - 80}
        stroke="#ff9e64" strokeWidth="3" markerEnd="url(#hit-arrow)" />
      <text x={cx - 138} y={cy + 4} textAnchor="middle" className="geo-label" fill="#ff9e64" fontWeight="600">
        b
      </text>

      {/* Right edge (loop b) */}
      <line x1={cx + 120} y1={cy + 80} x2={cx + 120} y2={cy - 80}
        stroke="#ff9e64" strokeWidth="3" markerEnd="url(#hit-arrow)" />
      <text x={cx + 138} y={cy + 4} textAnchor="middle" className="geo-label" fill="#ff9e64" fontWeight="600">
        b
      </text>

      {/* Base point */}
      <circle cx={cx - 120} cy={cy + 80} r="8" fill="#9ece6a" stroke="#0a0a0f" strokeWidth="2" />
      <text x={cx - 140} y={cy + 100} textAnchor="middle" className="geo-label geo-label-sm" fill="#9ece6a">
        base
      </text>

      {/* Surface label */}
      <text x={cx} y={cy + 4} textAnchor="middle" className="geo-annotation" fill="#7aa2f7">
        T²
      </text>

      {/* Title */}
      <text x={cx} y={36} textAnchor="middle" className="geo-title">
        Torus (T²)
      </text>
      <text x={cx} y={54} textAnchor="middle" className="geo-annotation" fill="#f7768e">
        base : T² &nbsp;&nbsp;|&nbsp;&nbsp; a, b : Path T² base base &nbsp;&nbsp;|&nbsp;&nbsp; surf : Square a a b b
      </text>
    </g>
  );
}

function renderGenericDiagram(node: ASTNode) {
  const cx = W / 2;
  const cy = H / 2 + 10;
  const cons = getConLabels(node);
  const pcons = getPConLabels(node);

  return (
    <g>
      <text x={cx} y={36} textAnchor="middle" className="geo-title">
        {node.label || 'Datatype'}
      </text>
      <text x={cx} y={54} textAnchor="middle" className="geo-annotation" fill="#c0caf5">
        Point constructors: {cons.length} &nbsp;|&nbsp; Path constructors: {pcons.length}
      </text>

      {/* Point constructors as dots arranged in a semicircle */}
      {cons.map((name, i) => {
        const angle = -Math.PI / 2 + (i / Math.max(cons.length - 1, 1)) * Math.PI;
        const radius = 90;
        const px = cx + Math.cos(angle) * radius;
        const py = cy + 20 + Math.sin(angle) * radius * 0.7;
        return (
          <g key={`con-${i}`}>
            <circle cx={px} cy={py} r="9" fill="#9ece6a" stroke="#0a0a0f" strokeWidth="2" />
            <text x={px} y={py + 24} textAnchor="middle" className="geo-label" fill="#9ece6a">
              {name}
            </text>
          </g>
        );
      })}

      {/* Path constructors as arrows between point constructors */}
      {pcons.map((pc, i) => {
        const fromIdx = Math.min(i, cons.length - 1);
        const toIdx = Math.min(i + 1, cons.length - 1);
        const angle0 = -Math.PI / 2 + (fromIdx / Math.max(cons.length - 1, 1)) * Math.PI;
        const angle1 = -Math.PI / 2 + (toIdx / Math.max(cons.length - 1, 1)) * Math.PI;
        const radius = 90;
        const x0 = cx + Math.cos(angle0) * radius;
        const y0 = cy + 20 + Math.sin(angle0) * radius * 0.7;
        const x1 = cx + Math.cos(angle1) * radius;
        const y1 = cy + 20 + Math.sin(angle1) * radius * 0.7;
        const mx = (x0 + x1) / 2;
        const my = (y0 + y1) / 2 - 30;
        return (
          <g key={`pcon-${i}`}>
            <path d={`M${x0},${y0} Q${mx},${my} ${x1},${y1}`}
              fill="none" stroke="#ff7a93" strokeWidth="2" strokeDasharray="6 3"
              markerEnd="url(#hit-arrow)" />
            <text x={mx} y={my - 8} textAnchor="middle" className="geo-label" fill="#ff7a93">
              {pc.name}
            </text>
          </g>
        );
      })}

      {/* Boundary conditions */}
      {pcons.length > 0 && (
        <text x={cx} y={H - 24} textAnchor="middle" className="geo-annotation">
          {pcons.map(pc => `${pc.name}: ${pc.face0} = ${pc.face1}`).join(' &nbsp;| ')}
        </text>
      )}
    </g>
  );
}

export default function HITDiagram({ node }: Props) {
  const hitType = detectHITType(node);

  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="geo-diagram">
      <defs>
        <marker id="hit-arrow" viewBox="0 0 10 10" refX="9" refY="5"
          markerWidth="6" markerHeight="6" orient="auto-start-reverse">
          <path d="M 0 0 L 10 5 L 0 10 z" fill="#ff7a93" />
        </marker>
      </defs>

      {hitType === 'S1' && renderS1Diagram(node)}
      {hitType === 'Torus' && renderTorusDiagram()}
      {hitType !== 'S1' && hitType !== 'Torus' && renderGenericDiagram(node)}
    </svg>
  );
}
